# Use an official Node.js runtime as the base image

FROM node:19

# Set the working directory in the container

WORKDIR /app

# Copy the package.json and package-lock.json files to the container

COPY app/package\*.json ./

# Install the application's dependencies

RUN npm install

# Copy the rest of the application's files to the container

COPY ./app .

RUN apt-get update && apt-get install -y iputils-ping default-mysql-client

# Expose port 3000 to the host machine

EXPOSE 3001

# Start the application

CMD ["npm", "start"]
